config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :groups
  mount GrapeApi => '/api'
  mount GrapeSwaggerRails::Engine => '/swagger'

  mount Sidekiq::Web => '/sidekiq'

  resources :reports
  
  resources :hdds
  resources :vms
  resources :projects
  root 'orders#calc'

  resource :login, only: %i[show create destroy]

  resources :users
  resources :orders do
    collection do
      get('check')
    end
  end

  resources :vms, only: [:index]

  get('hello/index')
end

app/models/vm.rb
class Vm < ApplicationRecord
  has_many :hdds
  has_and_belongs_to_many :projects
end

app/controllers/vms_controller.rb
class VmsController < ApplicationController
  before_action :set_vm, only: %i[show edit update destroy]

  # GET /vms or /vms.json
  def index
    @vms = Vm.all.map do |vm|
      {
        name: vm.name,
        cpu: vm.cpu,
        ram: vm.ram,
        hdds: vm.hdds.map { |h| [h.id, h.hdd_type, h.size] },
        projects: vm.projects.map { |p| [p.id, p.name, p.state] }
      }
    end
    render json: @vms
  end

  # GET /vms/1 or /vms/1.json
  def show; end

  # GET /vms/new
  def new
    @vm = Vm.new
  end

  # GET /vms/1/edit
  def edit; end

  # POST /vms or /vms.json
  def create
    @vm = Vm.new(vm_params)

    respond_to do |format|
      if @vm.save
        format.html { redirect_to vm_url(@vm), notice: 'Vm was successfully created.' }
        format.json { render :show, status: :created, location: @vm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vms/1 or /vms/1.json
  def update
    respond_to do |format|
      if @vm.update(vm_params)
        format.html { redirect_to vm_url(@vm), notice: 'Vm was successfully updated.' }
        format.json { render :show, status: :ok, location: @vm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vms/1 or /vms/1.json
  def destroy
    @vm.destroy

    respond_to do |format|
      format.html { redirect_to vms_url, notice: 'Vm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vm
    @vm = Vm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vm_params
    params.require(:vm).permit(:name, :cpu, :ram)
  end
end

app/views/vms/_form.html.erb
<%= form_with(model: vm) do |form| %>
  <% if vm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vm.errors.count, "error") %> prohibited this vm from being saved:</h2>

      <ul>
        <% vm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpu %>
    <%= form.number_field :cpu %>
  </div>

  <div class="field">
    <%= form.label :ram %>
    <%= form.number_field :ram %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vms/edit.html.erb
<h1>Editing Vm</h1>

<%= render 'form', vm: @vm %>

<%= link_to 'Show', @vm %> |
<%= link_to 'Back', vms_path %>

app/views/vms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpu</th>
      <th>Ram</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vms.each do |vm| %>
      <tr>
        <td><%= vm.name %></td>
        <td><%= vm.cpu %></td>
        <td><%= vm.ram %></td>
        <td><%= link_to 'Show', vm %></td>
        <td><%= link_to 'Edit', edit_vm_path(vm) %></td>
        <td><%= link_to 'Destroy', vm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vm', new_vm_path %>

app/views/vms/new.html.erb
<h1>New Vm</h1>

<%= render 'form', vm: @vm %>

<%= link_to 'Back', vms_path %>

app/views/vms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vm.name %>
</p>

<p>
  <strong>Cpu:</strong>
  <%= @vm.cpu %>
</p>

<p>
  <strong>Ram:</strong>
  <%= @vm.ram %>
</p>

<%= link_to 'Edit', edit_vm_path(@vm) %> |
<%= link_to 'Back', vms_path %>